name: RSS Fetcher Cron

on:
  schedule:
    - cron: '0 0 */2 * *' # Every 2 days at 00:00 UTC
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Install dependencies
        run: go mod download

      - name: Run Fetcher
        env:
          RSS_URL: ${{ secrets.RSS_URL }}
        run: go run main.go
